services:
  n8n-postgresql:
    container_name: n8n-postgresql
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .environment
    volumes:
      - n8n-postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
  n8n-redis:
    container_name: n8n-redis
    image: redis:latest
    command: >
      redis-server
      --requirepass 8D0ZsuvVT1UhnlgxajkCuD9TLumfhG5guawALKRUiDUjEPfI91
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - n8n-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  n8n-server:
    container_name: n8n-server
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    depends_on:
      n8n-postgresql:
        condition: service_healthy
      n8n-redis:
        condition: service_healthy
    env_file:
      - .environment
    volumes:
      - /home/lucidagreements/Volumes/automation:/home/node/data
      - n8n-server:/home/node/.n8n
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
  n8n-worker:
    image: n8nio/n8n:latest
    restart: always
    command: >
      worker
    depends_on:
      n8n-server:
        condition: service_healthy
    env_file:
      - .environment
    volumes:
      - /home/lucidagreements/Volumes/automation:/home/node/data
      - n8n-worker:/home/node/.n8n
    deploy:
      replicas: 4

volumes:
  n8n-postgresql:
    name: n8n-postgresql
  n8n-redis:
    name: n8n-redis
  n8n-server:
    name: n8n-server
  n8n-worker:
    name: n8n-worker
